// Generated by CoffeeScript 1.6.1
(function() {
  var BigWordToken;

  BigWordToken = (function() {

    function BigWordToken(args) {
      this.type = args.type;
      this.value = args.value;
      this.position = args.position;
    }

    return BigWordToken;

  })();

}).call(this);
