// Generated by CoffeeScript 1.6.1
(function() {
  var SmallWordToken;

  SmallWordToken = (function() {

    function SmallWordToken(args) {
      this.type = args.type;
      this.value = args.value;
      this.position = args.position;
    }

    return SmallWordToken;

  })();

}).call(this);
