// Generated by CoffeeScript 1.8.0
(function() {
  window.Token = (function() {
    var LOG;

    LOG = new Logger({
      module: 'tokenizer',
      prefix: 'TOKEN'
    });

    function Token(options) {
      this.type = options != null ? options.type : void 0;
      this.value = options != null ? options.value : void 0;
    }

    return Token;

  })();

}).call(this);
