// Generated by CoffeeScript 1.6.1
(function() {
  var WordTokenizer;

  WordTokenizer = (function() {

    function WordTokenizer() {}

    WordTokenizer.getSmallWordToken = function() {
      return new SmallWordToken({
        type: 'ALPHA_NUM',
        word: 'blah',
        position: {
          row: 0,
          col: 0
        }
      });
    };

    WordTokenizer.getBigWordToken = function() {
      return new BigWordToken({
        type: 'WORD',
        word: 'blah!@#',
        position: {
          row: 0,
          col: 0
        }
      });
    };

    return WordTokenizer;

  })();

}).call(this);
