// Generated by CoffeeScript 1.6.1
(function() {
  var WordToken;

  WordToken = (function() {

    function WordToken(args) {
      this.type = args.type;
      this.word = args.word;
      this.position = args.position;
    }

    return WordToken;

  })();

}).call(this);
